# config for training


trainer:
  checkpoint: "./model_pickle/Conformer_PIT_re2/mono_d"
  # checkpoint: "./model_pickle/Conformer_PIT/7ch_v82_SASDR_IPD"
  # checkpoint: "./model_pickle/Conformer_PIT/7ch_v60_SISNR_SA_sincosIPD"
  optimizer: "adamW"
  # 1e-3 => str
  # 1.0e-3 => float
  lr: 2.0e-4
  weight_decay: 1.0e-2
  clip_norm: 5
  min_lr: 1.0e-10
  patience: 2
  factor: 0.7
  disturb_std: 0
  loss : 'SA_SDR' # A_SDR, SA_SDR, MSE
  scale_inv: false
  mvn: true
  apply_log: false
  IPD_sincos: false

model_type: "Conformer"

# rir_conf:
rir_conf:
  RT_list: [0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]
  rir_dir: "./RIR_filter_v9"

noise_dir: "/home/Uihyeop/colorednoise_v9_short/"
# noise_dir: "/home/nas/user/Uihyeop/DB/wsj0-mix/2speakers/wav16k/colorednoise_v9_short/"

  # room_conf: ["medium", "small"]
crm : false

MVDR: false


model:
  noise_flag: false
  in_features: 257
  num_mics : 1
  num_spks: 2
  activation : 'sigmoid' # relu, sigmoid
  conformer_conf:
    attention_dim: 256
    attention_heads: 4
    dropout_rate: 0.1
    kernel_size: 33
    linear_units: 1024
    num_blocks: 16

spectrogram_reader:
  frame_shift: 256
  frame_length: 512
  window: "hann"
  transpose: true
  # NOTE: do not apply log here
  # false => produce psm
  # true  => produce irm

# train_scp_conf:
#   mixture: "scp_librimix_css_v1_segment/tr_mix.scp"
#   spk1: "scp_librimix_css_v1_segment/tr_s1.scp"
#   spk2: "scp_librimix_css_v1_segment/tr_s2.scp"

# valid_scp_conf:
#   mixture: "scp_librimix_css_v1_segment/cv_mix.scp"
#   spk1: "scp_librimix_css_v1_segment/cv_s1.scp"
#   spk2: "scp_librimix_css_v1_segment/cv_s2.scp"

train_scp_conf:
  mixture: "scp/scp_css_v3_segment/tr_mix.scp"
  spk1: "scp/scp_css_v3_segment/tr_s1.scp"
  spk2: "scp/scp_css_v3_segment/tr_s2.scp"

valid_scp_conf:
  mixture: "scp/scp_css_v3_segment/cv_mix.scp"
  spk1: "scp/scp_css_v3_segment/cv_s1.scp"
  spk2: "scp/scp_css_v3_segment/cv_s2.scp"

test_scp_conf:
  mixture: "scp/scp_css_v3_segment/tt_mix.scp"
  spk1: "scp/scp_css_v3_segment/tt_s1.scp"
  spk2: "scp/scp_css_v3_segment/tt_s2.scp"


dataloader:
  shuffle: true
  batch_size: 10
  drop_last: false
  num_workers: 5
  max_frame : 700

