# config for training

trainer:
  checkpoint: "./model_pickle/DPMCN/7ch_v15_no_beta_d_norm"
  # checkpoint: "./model_pickle/DPMCN/7ch_v15"
  # checkpoint: "./model_pickle/UConformer_PIT/7ch_v16_SASDR_IPD_Large_Libri"
  # checkpoint: "./model_pickle/Conformer_PIT/7ch_v60_SISNR_SA_sincosIPD"
  optimizer: "adamW"
  # 1e-3 => str
  # 1.0e-3 => float
  lr: 2.0e-4
  weight_decay: 1.0e-2
  clip_norm: 5
  min_lr: 1.0e-10
  patience: 1
  factor: 0.8
  disturb_std: 0
  loss : 'SA_SDR' # A_SDR, SA_SDR, MSE
  scale_inv: false
  mvn: false
  apply_log: false
  IPD_sincos: false

MVDR: false

model_type: "DPMCN_v15"

rir_conf:
  RT_list: [0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]
  rir_dir: "./RIR_filter_v9"
# noise_dir: "/home/nas/user/Uihyeop/DB/wsj0-mix/2speakers/wav16k/colorednoise_v9/"
noise_dir: "/home/work/data_Uihyeop/data/colorednoise_v9_short/"
# noise_dir: "/home/work/data_Uihyeop/data/Reverb_air_noise/NOISE_seg_7ch/"

  # room_conf: ["medium", "small"]
crm : false

model:
  noise_flag: false
  in_features: 257
  num_mics : 7
  num_spks: 2
  conformer_conf:
    attention_dim_F: 128
    attention_dim_C: 64
    attention_heads_F: 4
    attention_heads_C: 2
    dropout_rate: 0.05
    kernel_size: 33
    linear_units_F: 512
    linear_units_C: 256
    N_intra : 2
    N_inter : 1
    N_repeat : 4
    GRN_opt: true
    beta : 'fixed_no' # vector, scalar, fixed_mag, fixed_no
    
spectrogram_reader:
  frame_shift: 256
  frame_length: 512
  window: "hann"
  transpose: true
  # NOTE: do not apply log here
  # false => produce psm
  # true  => produce irm

# train_scp_conf:
#   mixture: "scp_librimix_css_v1_segment/tr_mix.scp"
#   spk1: "scp_librimix_css_v1_segment/tr_s1.scp"
#   spk2: "scp_librimix_css_v1_segment/tr_s2.scp"

# valid_scp_conf:
#   mixture: "scp_librimix_css_v1_segment/cv_mix.scp"
#   spk1: "scp_librimix_css_v1_segment/cv_s1.scp"
#   spk2: "scp_librimix_css_v1_segment/cv_s2.scp"

train_scp_conf:
  mixture: "scp_css_v3_segment/tr_mix.scp"
  spk1: "scp_css_v3_segment/tr_s1.scp"
  spk2: "scp_css_v3_segment/tr_s2.scp"

valid_scp_conf:
  mixture: "scp_css_v3_segment/cv_mix.scp"
  spk1: "scp_css_v3_segment/cv_s1.scp"
  spk2: "scp_css_v3_segment/cv_s2.scp"

test_scp_conf:
  mixture: "scp_css_v3_segment/tt_mix.scp"
  spk1: "scp_css_v3_segment/tt_s1.scp"
  spk2: "scp_css_v3_segment/tt_s2.scp"


dataloader:
  shuffle: true
  batch_size: 8
  drop_last: false
  num_workers: 5
  max_frame : 700

inference:
  check_point_dir: "./model_pickle/DPMCN_v15/epoch.112.pkl"
  save_conf:
    wav_norm: false
  CSS_conf:
    CSS: false
    # N_h: 3.6
    # N_c: 2.4
    # N_f: 1.2
    N_h: 1.2
    N_c: 0.8
    N_f: 0.4
