# config for training

trainer:
  checkpoint: "./tune/2spk_pit_psm_l"
  optimizer: "adam"
  lr: 1.0e-3
  momentum: 0.9
  weight_decay: 1.0e-5
  clip_norm: 200
  min_lr: 1.0e-10
  patience: 0
  factor: 0.7
  disturb_std: 0

model:
  num_spks: 2
  rnn: "lstm"
  num_layers: 3
  hidden_size: 896
  dropout: 0.5
  non_linear: "relu"
  bidirectional: true

spectrogram_reader:
  frame_shift: 128
  frame_length: 256
  window: "hann"
  transpose: true
  # false => produce psm
  # true  => produce irm
  apply_abs: false

train_scp_conf:
  mixture: "./data/2spk/train/mix.scp"
  spk1: "./data/2spk/train/spk1.scp"
  spk2: "./data/2spk/train/spk2.scp"

valid_scp_conf:
  mixture: "./data/2spk/dev/mix.scp"
  spk1: "./data/2spk/dev/spk1.scp"
  spk2: "./data/2spk/dev/spk2.scp"

debug_scp_conf:
  mixture: "./data/tune/mix.scp"
  spk1: "./data/tune/spk1.scp"
  spk2: "./data/tune/spk2.scp"

dataloader:
  shuffle: true
  batch_size: 8
  drop_last: false
  apply_log: false
  mvn_dict: "data/linear.cmvn.dict"

